name: CI

on:
  push:
    branches: 
      - rama-SergioLozano
      - rama-JuliaMejia
      - rama-CarlosRodriguez
  pull_request:
    branches: 
      - rama-SergioLozano
      - rama-JuliaMejia
      - rama-CarlosRodriguez

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
